name: Rust

on:
  push:
    branches:
      - master
  pull_request:
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 1

    - run: rustup toolchain install stable --profile minimal --no-self-update

    - uses: Swatinem/rust-cache@v2

    - name: Code linting
      continue-on-error: true
      run: cargo clippy --workspace --all-targets --all-features -- -D warnings
      
    - name: Code formatting
      continue-on-error: true
      run: cargo fmt --all --check
      
    - name: Build
      continue-on-error: true
      run: cargo build

    - name: Run tests
      continue-on-error: true
      run: cargo test --workspace --all-features --all-targets

    - name: Check docs
      continue-on-error: true
      env:
        RUSTDOCFLAGS: "-D rustdoc::all -A rustdoc::private-doc-tests"
      run: cargo doc --package am4 --all-features --no-deps